### PR TITLE
simplify stuff

### PR DESCRIPTION
**Pull request by max-mapper**
this removes almost everything, including the `xmlhttprequest` polyfill. I couldn't make heads or tails of the previous build system (required ruby and makefiles).

this adds browserling tests, and will make it a lot easier to contribute to this repo. we'll need to add back a cross browser xhr polyfill, but it can be done in a sane way with tests this time.

at this time iriscouch/browser-request doesn't work in FF but this one does

### CODE REVIEW

**Comment by juliangruber** [comment]
can you publish this please?

**Comment by max-mapper** [comment]
@juliangruber upvote this issue https://github.com/iriscouch/browser-request/pull/18

**Comment by jhs** [comment]
@maxogden Merged #18. Also I added you to the maintainers list in npm, and in my heart if I'm honest.

I am afraid to do a publish without reviewing your changes more thoroughly. Mostly I suspect my build script may be out of date. But if you want to publish, you are welcome.

**Comment by max-mapper** [comment]
@jhs can you do this so that the testling CI badge starts showing up in the readme? https://ci.testling.com/#hook

**Pull request merged**
